apiVersion: v2
name: netbox
version: 4.1.4
# renovate: netbox-community/netbox
appVersion: v3.3.2
description: IP address management (IPAM) and data center infrastructure management (DCIM) tool
home: https://github.com/chaosdorf/helm-charts
icon: https://raw.githubusercontent.com/netbox-community/netbox/develop/docs/netbox_logo.png
maintainers:
- name: Chaosdorf
  email: mail@chaosdorf.de
  url: https://chaosdorf.de
dependencies:
- name: postgresql
  version: 12.6.4
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 17.11.7
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
