apiVersion: v2
name: netbox
version: 4.1.10
# renovate: image=netboxcommunity/netbox
appVersion: v4.1.4
description: IP address management (IPAM) and data center infrastructure management (DCIM) tool
home: https://github.com/chaosdorf/helm-charts/tree/main/charts/netbox
icon: https://raw.githubusercontent.com/netbox-community/netbox/develop/docs/netbox_logo.png
maintainers:
- name: Chaosdorf
  email: mail@chaosdorf.de
  url: https://chaosdorf.de
dependencies:
- name: postgresql
  version: 12.12.10
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 17.17.1
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
