{{- if .Values.coturn.enabled }}
{{- $portRange := untilStep (int .Values.coturn.ports.from) (int (add1 .Values.coturn.ports.to)) 1 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}-coturn
  labels:
{{ include "matrix.labels" . | indent 4 }}
spec:
  type: {{ .Values.coturn.service.type }}
  ports:
    {{- range $portRange }}
    - port: {{ . }}
      targetPort: {{ . }}
      {{- if eq $.Values.coturn.service.type "NodePort" }}
      nodePort: {{ . }}
      {{- end }}
      protocol: UDP
      name: turn-{{ . }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "matrix.name" . }}-coturn
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
