{{- if or .Values.bridges.whatsapp.enabled .Values.bridges.discord.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "matrix.fullname" . }}-bridges
  labels:
{{ include "matrix.labels" . | indent 4}}
spec:
  storageClassName: {{ .Values.bridges.volume.storageClass }}
  accessModes:
    - {{ .Values.bridges.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.bridges.volume.capacity }}
{{- end }}
