apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix.fullname" . }}-homeserver-yaml
  labels:
{{ include "matrix.labels" . | nindent 4}}
data:
  homeserver.yaml: |
    {{ include "homeserver.yaml" . | nindent 4 }}
