apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrix.fullname" . }}-synapse
  labels:
{{ include "matrix.labels" . | indent 4 }}
spec:
  type: {{ .Values.synapse.service.type }}
  ports:
    - port: {{ .Values.synapse.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.synapse.metrics.enabled }}
    - port: {{ .Values.synapse.metrics.port }}
      targetPort: prometheus-http
      protocol: TCP
      name: prometheus-http
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "matrix.name" . }}-synapse
    app.kubernetes.io/instance: {{ .Release.Name }}
