apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbox.fullname" . }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "netbox.labels" . | indent 4 }}
data:
  configuration.py: |
    import re
    import yaml

    from pathlib import Path

    def _load_yaml():
      extraConfigBase = Path('/run/config/extra')
      configFiles = [Path('/run/config/netbox/netbox.yaml')]

      configFiles.extend(sorted(extraConfigBase.glob('*/*.yaml')))

      for configFile in configFiles:
        with open(configFile, 'r') as f:
          config = yaml.safe_load(f)

        globals().update(config)

    def _load_secret(name, key):
      path = "/run/secrets/{name}/{key}".format(name=name, key=key)
      with open(path, 'r') as f:
        return f.read()

    _load_yaml()

    DATABASE['PASSWORD'] = _load_secret('netbox', 'db_password')
    EMAIL['PASSWORD'] = _load_secret('netbox', 'email_password')
    NAPALM_PASSWORD = _load_secret('netbox', 'napalm_password')
    REDIS['tasks']['PASSWORD'] = _load_secret('netbox', 'redis_tasks_password')
    REDIS['caching']['PASSWORD'] = _load_secret('netbox', 'redis_cache_password')
    SECRET_KEY = _load_secret('netbox', 'secret_key')

    # Post-process certain values
    CORS_ORIGIN_REGEX_WHITELIST = [re.compile(r) for r
                                   in CORS_ORIGIN_REGEX_WHITELIST]
    {{- if and (not .Values.redis.enabled) .Values.tasksRedis.sentinels }}
    REDIS['tasks']['SENTINELS'] = [tuple(x.split(r":")) for x
                                   in REDIS['tasks']['SENTINELS']]
    {{- end }}
    {{- if and (not .Values.redis.enabled) .Values.cachingRedis.sentinels }}
    REDIS['caching']['SENTINELS'] = [tuple(x.split(r":")) for x
                                     in REDIS['caching']['SENTINELS']]
    {{- end }}

  netbox.yaml: |
    ALLOWED_HOSTS: {{ toJson .Values.allowedHosts }}

    DATABASE:
      {{ if .Values.postgresql.enabled -}}
      HOST: {{ include "netbox.postgresql.fullname" . | quote }}
      USER: {{ .Values.postgresql.postgresqlUsername | quote }}
      NAME: {{ .Values.postgresql.postgresqlDatabase | quote }}
      PORT: {{ .Values.postgresql.service.port | int }}
      {{- else -}}
      HOST: {{ .Values.externalDatabase.host | quote }}
      USER: {{ .Values.externalDatabase.username | quote }}
      NAME: {{ .Values.externalDatabase.database | quote }}
      PORT: {{ .Values.externalDatabase.port | int }}
      {{- end }}
      OPTIONS:
        sslmode: {{ .Values.externalDatabase.sslMode | quote }}
      CONN_MAX_AGE: {{ .Values.externalDatabase.connMaxAge | int }}

    ADMINS: {{ toJson .Values.admins }}
    ALLOWED_URL_SCHEMES: {{ toJson .Values.allowedUrlSchemes }}
    BANNER_TOP: {{ .Values.banner.top | quote }}
    BANNER_BOTTOM: {{ .Values.banner.bottom | quote }}
    BANNER_LOGIN: {{ .Values.banner.login | quote }}
    BASE_PATH: {{ .Values.basePath | quote }}
    CHANGELOG_RETENTION: {{ int .Values.changelogRetention }}
    CORS_ORIGIN_ALLOW_ALL: {{ toJson .Values.cors.originAllowAll }}
    CORS_ORIGIN_WHITELIST: {{ toJson .Values.cors.originWhitelist }}
    CORS_ORIGIN_REGEX_WHITELIST: {{ toJson .Values.cors.originRegexWhitelist }}
    DEBUG: {{ toJson .Values.debug }}

    EMAIL:
      SERVER: {{ .Values.email.server | quote }}
      PORT: {{ .Values.email.port | int }}
      USERNAME: {{ .Values.email.username | quote }}
      USE_SSL: {{ toJson .Values.email.useSSL }}
      USE_TLS: {{ toJson .Values.email.useTLS }}
      TIMEOUT: {{ .Values.email.timeout | int }}
      FROM_EMAIL: {{ toJson .Values.email.from }}

    ENFORCE_GLOBAL_UNIQUE: {{ toJson .Values.enforceGlobalUnique }}
    EXEMPT_VIEW_PERMISSIONS: {{ toJson .Values.exemptViewPermissions }}
    GRAPHQL_ENABLED: {{ toJson .Values.graphQlEnabled }}
    HTTP_PROXIES: {{ toJson .Values.httpProxies }}
    INTERNAL_IPS: {{ toJson .Values.internalIPs }}
    LOGGING: {{ toJson .Values.logging }}
    LOGIN_PERSISTENCE: {{ toJson .Values.loginPersistence }}
    LOGIN_REQUIRED: {{ toJson .Values.loginRequired }}
    LOGIN_TIMEOUT: {{ int .Values.loginTimeout }}
    MAINTENANCE_MODE: {{ toJson .Values.maintenanceMode }}
    MAPS_URL: {{ .Values.mapsUrl | quote }}
    MAX_PAGE_SIZE: {{ int .Values.maxPageSize }}
    MEDIA_ROOT: /opt/netbox/netbox/media
    STORAGE_BACKEND: {{ .Values.storageBackend | quote }}
    STORAGE_CONFIG:  {{ toJson .Values.storageConfig }}
    METRICS_ENABLED: {{ toJson .Values.metricsEnabled }}
    NAPALM_USERNAME: {{ .Values.napalm.username | quote }}
    NAPALM_TIMEOUT: {{ int .Values.napalm.timeout }}
    NAPALM_ARGS: {{ toJson .Values.napalm.args }}
    PAGINATE_COUNT: {{ int .Values.paginateCount }}
    PLUGINS: {{ toJson .Values.plugins }}
    PLUGINS_CONFIG: {{ toJson .Values.pluginsConfig }}
    PREFER_IPV4: {{ toJson .Values.preferIPv4 }}
    RACK_ELEVATION_DEFAULT_UNIT_HEIGHT: {{ int .Values.rackElevationDefaultUnitHeight }}
    RACK_ELEVATION_DEFAULT_UNIT_WIDTH: {{ int .Values.rackElevationDefaultUnitWidth }}
    REMOTE_AUTH_ENABLED: {{ toJson .Values.remoteAuth.enabled }}
    REMOTE_AUTH_BACKEND: {{ .Values.remoteAuth.backend | quote }}
    REMOTE_AUTH_HEADER: {{ .Values.remoteAuth.header | quote }}
    REMOTE_AUTH_AUTO_CREATE_USER: {{ toJson .Values.remoteAuth.autoCreateUser }}
    REMOTE_AUTH_DEFAULT_GROUPS: {{ toJson .Values.remoteAuth.defaultGroups }}
    REMOTE_AUTH_DEFAULT_PERMISSIONS: {{ toJson .Values.remoteAuth.defaultPermissions }}
    REMOTE_AUTH_GROUP_SYNC_ENABLED: {{ toJson .Values.remoteAuth.groupSyncEnabled }}
    REMOTE_AUTH_GROUP_HEADER: {{ .Values.remoteAuth.groupHeader | quote }}
    REMOTE_AUTH_SUPERUSER_GROUPS: {{ toJson .Values.remoteAuth.superuserGroups }}
    REMOTE_AUTH_SUPERUSERS: {{ toJson .Values.remoteAuth.superusers }}
    REMOTE_AUTH_STAFF_GROUPS: {{ toJson .Values.remoteAuth.staffGroups }}
    REMOTE_AUTH_STAFF_USERS: {{ toJson .Values.remoteAuth.staffUsers }}
    REMOTE_AUTH_GROUP_SEPARATOR: {{ .Values.remoteAuth.groupSeparator | quote }}
    RELEASE_CHECK_URL: {{ toJson .Values.releaseCheck.url }}

    REDIS:
      tasks:
        {{ if .Values.redis.enabled -}}
        HOST: {{ printf "%s-master" (include "netbox.redis.fullname" .) | quote }}
        PORT: {{ .Values.redis.master.service.port | int }}
        {{- else if .Values.tasksRedis.sentinels -}}
        SENTINELS: {{ toJson .Values.tasksRedis.sentinels }}
        SENTINEL_SERVICE: {{ .Values.tasksRedis.sentinelService | quote }}
        SENTINEL_TIMEOUT: {{ .Values.tasksRedis.sentinelTimeout | int }}
        {{- else -}}
        HOST: {{ .Values.tasksRedis.host | quote }}
        PORT: {{ .Values.tasksRedis.port | int}}
        {{- end }}
        DATABASE: {{ int .Values.tasksRedis.database }}
        SSL: {{ toJson .Values.tasksRedis.ssl }}
        INSECURE_SKIP_TLS_VERIFY: {{ toJson .Values.tasksRedis.insecureSkipTlsVerify }}
      caching:
        {{ if .Values.redis.enabled -}}
        HOST: {{ printf "%s-master" (include "netbox.redis.fullname" .) | quote }}
        PORT: {{ .Values.redis.master.service.port | int }}
        {{- else if .Values.cachingRedis.sentinels -}}
        SENTINELS: {{ toJson .Values.cachingRedis.sentinels }}
        SENTINEL_SERVICE: {{ .Values.cachingRedis.sentinelService | quote }}
        SENTINEL_TIMEOUT: {{ .Values.cachingRedis.sentinelTimeout | int }}
        {{- else -}}
        HOST: {{ .Values.cachingRedis.host | quote }}
        PORT: {{ .Values.cachingRedis.port | int}}
        {{- end }}
        DATABASE: {{ int .Values.cachingRedis.database }}
        SSL: {{ toJson .Values.cachingRedis.ssl }}
        INSECURE_SKIP_TLS_VERIFY: {{ toJson .Values.cachingRedis.insecureSkipTlsVerify }}

    REPORTS_ROOT: /opt/netbox/netbox/reports
    RQ_DEFAULT_TIMEOUT: {{ .Values.rqDefaultTimeout | int }}
    SCRIPTS_ROOT: /opt/netbox/netbox/scripts
    SESSION_COOKIE_NAME: {{ .Values.sessionCookieName }}
    TIME_ZONE: {{ .Values.timeZone | quote }}
    DATE_FORMAT: {{ .Values.dateFormat | quote }}
    SHORT_DATE_FORMAT: {{ .Values.shortDateFormat | quote }}
    TIME_FORMAT: {{ .Values.timeFormat | quote }}
    SHORT_TIME_FORMAT: {{ .Values.shortTimeFormat | quote }}
    DATETIME_FORMAT: {{ .Values.dateTimeFormat | quote }}
    SHORT_DATETIME_FORMAT: {{ .Values.shortDateTimeFormat | quote }}

  {{- if eq .Values.remoteAuth.backend "netbox.authentication.LDAPBackend" }}

  ldap_config.py: |
    import yaml
    import ldap
    from django_auth_ldap.config import LDAPSearch
    from importlib import import_module
    def _load_yaml():
      with open('/run/config/netbox/ldap.yaml', 'r') as f:
        config = yaml.safe_load(f)
      globals().update(config)
    def _load_secret(name, key):
      path = "/run/secrets/{name}/{key}".format(name=name, key=key)
      with open(path, 'r') as f:
        return f.read()
    # Import and return the group type based on string name
    def _import_group_type(group_type_name):
        mod = import_module('django_auth_ldap.config')
        try:
            return getattr(mod, group_type_name)()
        except:
            return None
    _load_yaml()
    AUTH_LDAP_BIND_PASSWORD = _load_secret('netbox', 'ldap_bind_password')
    # The following may be needed if you are binding to Active Directory.
    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_REFERRALS: 0
    }
    AUTH_LDAP_USER_SEARCH = LDAPSearch(AUTH_LDAP_USER_SEARCH_BASEDN,
                                      ldap.SCOPE_SUBTREE,
                                      "(" + AUTH_LDAP_USER_SEARCH_ATTR + "=%(user)s)")
    AUTH_LDAP_GROUP_SEARCH = LDAPSearch(AUTH_LDAP_GROUP_SEARCH_BASEDN, ldap.SCOPE_SUBTREE,
                                  "(objectClass=" + AUTH_LDAP_GROUP_SEARCH_CLASS + ")")
    AUTH_LDAP_GROUP_TYPE = _import_group_type(AUTH_LDAP_GROUP_TYPE)
    # Define special user types using groups. Exercise great caution when assigning superuser status.
    AUTH_LDAP_USER_FLAGS_BY_GROUP = {
        "is_active": AUTH_LDAP_REQUIRE_GROUP,
        "is_staff": {{ .Values.remoteAuth.ldap.isAdminDn | quote }},
        "is_superuser": {{ .Values.remoteAuth.ldap.isSuperUserDn | quote }}
    }
    # Populate the Django user from the LDAP directory.
    AUTH_LDAP_USER_ATTR_MAP = {
        "first_name": {{ .Values.remoteAuth.ldap.attrFirstName | quote }},
        "last_name": {{ .Values.remoteAuth.ldap.attrLastName | quote }},
        "email": {{ .Values.remoteAuth.ldap.attrMail | quote }}
    }

  ldap.yaml: |
    AUTH_LDAP_SERVER_URI: {{ .Values.remoteAuth.ldap.serverUri | quote }}
    AUTH_LDAP_BIND_DN: {{ .Values.remoteAuth.ldap.bindDn | quote }}
    AUTH_LDAP_START_TLS: {{ toJson .Values.remoteAuth.ldap.startTls }}
    LDAP_IGNORE_CERT_ERRORS: {{ toJson .Values.remoteAuth.ldap.ignoreCertErrors }}
    AUTH_LDAP_USER_DN_TEMPLATE: {{ default nil .Values.remoteAuth.ldap.userDnTemplate }}
    AUTH_LDAP_USER_SEARCH_BASEDN: {{ .Values.remoteAuth.ldap.userSearchBaseDn | quote }}
    AUTH_LDAP_USER_SEARCH_ATTR: {{ .Values.remoteAuth.ldap.userSearchAttr | quote }}
    AUTH_LDAP_GROUP_SEARCH_BASEDN: {{ .Values.remoteAuth.ldap.groupSearchBaseDn | quote }}
    AUTH_LDAP_GROUP_SEARCH_CLASS: {{ .Values.remoteAuth.ldap.groupSearchClass | quote }}
    AUTH_LDAP_GROUP_TYPE: {{ .Values.remoteAuth.ldap.groupType | quote }}
    AUTH_LDAP_REQUIRE_GROUP: {{ .Values.remoteAuth.ldap.requireGroupDn | quote }}
    AUTH_LDAP_FIND_GROUP_PERMS: {{ toJson .Values.remoteAuth.ldap.findGroupPerms }}
    AUTH_LDAP_MIRROR_GROUPS: {{ toJson .Values.remoteAuth.ldap.mirrorGroups }}
    AUTH_LDAP_MIRROR_GROUPS_EXCEPT: {{ toJson .Values.remoteAuth.ldap.mirrorGroupsExcept }}
    AUTH_LDAP_CACHE_TIMEOUT: {{ int .Values.remoteAuth.ldap.cacheTimeout }}
  {{- end }}
  {{ range $index, $config := .Values.extraConfig -}}
  {{- if $config.values }}
  extra-{{ $index }}.yaml: |
    {{- toYaml $config.values | nindent 4 }}
  {{- end }}
  {{ end -}}
