name: Renovate
on:
  push:

jobs:
  renovate:
    name: Dry Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Renovate Dry Run
        uses: renovatebot/github-action@v39.0.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_DRY_RUN: lookup
          RENOVATE_USERNAME: renovate-bot
          RENOVATE_GIT_AUTHOR: renovate bot <renovate@example.org>
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: "debug"
