apiVersion: v2
name: engelsystem
version: 0.1.0
# renovate: image=chaosdorf/engelsystem
appVersion: 3.3.1
description: A Helm chart for Engelsystem
type: application
home: https://github.com/chaosdorf/helm-charts/tree/main/charts/engelsystem
icon: https://raw.githubusercontent.com/chaosdorf/engelsystem/main/resources/assets/icons/angel.svg
maintainers:
- name: Chaosdorf
  email: mail@chaosdorf.de
  url: https://chaosdorf.de
dependencies:
- name: mariadb
  version: 13.1.2
  repository: https://charts.bitnami.com/bitnami
  condition: mariadb.enabled
